# Dockerfile_googlestt
FROM python:3.8

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 나머지 소스 코드 복사
COPY . .

# Flask 서버 실행 포트 설정
EXPOSE 5002

# Flask 애플리케이션 실행
CMD ["python", "googlestt.py"]
